export const TimeOptions = ({ className, ...props }) => (
  <form className={className}>
    <label>
      <input
        type="radio"
        name="select-time"
        value={1}
        onClick={props.handleTimeframe}
      />
      <span></span>
    </label>
    <p>1d</p>
    <label>
      <input
        type="radio"
        name="select-time"
        value={7}
        onClick={props.handleTimeframe}
      />
      <span></span>
    </label>
    <p>7d</p>
    <label>
      <input
        type="radio"
        name="select-time"
        value={30}
        onClick={props.handleTimeframe}
      />
      <span></span>
    </label>
    <p>30d</p>
    <label>
      <input
        type="radio"
        name="select-time"
        value={90}
        onClick={props.handleTimeframe}
      />
      <span></span>
    </label>
    <p>90d</p>
    <label>
      <input
        type="radio"
        name="select-time"
        value={360}
        onClick={props.handleTimeframe}
      />
      <span></span>
    </label>
    <p>1y</p>
    <label>
      <input
        type="radio"
        name="select-time"
        value={5000}
        onChange={props.handleTimeframe}
      />
      <span></span>
    </label>
    <p>Max</p>
  </form>
);
